
name: Master APP3 Deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
    
jobs:
  set-parameters:
    name: set-parameters
    runs-on: ubuntu-latest
    outputs: 
      branch: ${{ steps.app_params.outputs.branch }}
    steps:
      - name: Set App Parameters
        id: app_params
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

  echo-branch:
    name: echo-branch
    runs-on: ubuntu-latest
    needs: [ set-parameters ]
    env:
      BRANCH: "${{ needs.set-parameters.outputs.branch }}"
    steps:
      - name: ECHO
        run: |
          echo "Master APP3 Deploy"
          echo "Branch name is $BRANCH"



