
name: Staging APP2 Deploy
on:
  pull_request_review:
    branches:
      - main
    types: [submitted]
    
jobs:
  set-parameters:
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.head.ref, 'app2')
    name: set-parameters
    runs-on: ubuntu-latest
    outputs: 
      branch_ref: ${{ steps.app_params.outputs.branch }}
    steps:
      - name: Set App Parameters
        id: app_params
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

  echo-branch:
    name: echo-branch
    runs-on: ubuntu-latest
    needs: [ set-parameters ]
    env:
      BRANCH: "${{ needs.set-parameters.outputs.branch }}"
    steps:
      - name: ECHO
        run: |
          echo "Staging APP2 Deploy"
          echo "Branch_ref name is $BRANCH"
          echo "head_ref"
          echo '${{ github.event.pull_request.head.ref }}'

